// Copyright (C) 2025 Voltual
// 本程序是自由软件：你可以根据自由软件基金会发布的 GNU 通用公共许可证第3版
// （或任意更新的版本）的条款重新分发和/或修改它。
// 本程序是基于希望它有用而分发的，但没有任何担保；甚至没有适销性或特定用途适用性的隐含担保。
// 有关更多细节，请参阅 GNU 通用公共许可证。
//
// 你应该已经收到了一份 GNU 通用公共许可证的副本
// 如果没有，请查阅 <http://www.gnu.org/licenses/>。
package me.voltual.vb.core.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0049C0)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF1859CD)
val onPrimaryContainerLight = Color(0xFFE0E6FF)
val secondaryLight = Color(0xFF6B3FA0)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEBDCFF)
val onSecondaryContainerLight = Color(0xFF260058)
val tertiaryLight = Color(0xFFB07D00) 
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFE086)
val onTertiaryContainerLight = Color(0xFF241A00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FC)
val onBackgroundLight = Color(0xFF1A1C22)
val surfaceLight = Color(0xFFF9F9FC)
val onSurfaceLight = Color(0xFF1A1C22)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44464F)
val outlineLight = Color(0xFF757780)
val outlineVariantLight = Color(0xFFC5C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFADC6FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFF9F9FC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E7EE)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)
val primaryDark = Color(0xFF3B82F6)
val onPrimaryDark = Color(0xFF002B75)
val primaryContainerDark = Color(0xFF003E9C)
val onPrimaryContainerDark = Color(0xFFD8E2FF)
val secondaryDark = Color(0xFFA855F7)
val onSecondaryDark = Color(0xFF3F007D)
val secondaryContainerDark = Color(0xFF5B00B0)
val onSecondaryContainerDark = Color(0xFFF1DBFF)
val tertiaryDark = Color(0xFFFACC15) 
val onTertiaryDark = Color(0xFF3A3000)
val tertiaryContainerDark = Color(0xFF544600)
val onTertiaryContainerDark = Color(0xFFFFE174)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0A0B10) 
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF10121A) 
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF1E212E)
val onSurfaceVariantDark = Color(0xFFC5C6D0)
val outlineDark = Color(0xFF44474F) 
val outlineVariantDark = Color(0xFF1E212E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF0056D6)
val surfaceDimDark = Color(0xFF10121A)
val surfaceBrightDark = Color(0xFF363945)
val surfaceContainerLowestDark = Color(0xFF05060A)
val surfaceContainerLowDark = Color(0xFF181A24)
val surfaceContainerDark = Color(0xFF1C1E2A)
val surfaceContainerHighDark = Color(0xFF262938)
val surfaceContainerHighestDark = Color(0xFF313547)

// 特殊日志与状态配色
val message_like_bg = Color(0xFFE8F5E9)
val message_comment_bg = Color(0xFFE3F2FD)
val message_default_bg = Color(0xFFFFF9C4)
val billing_income = Color(0xFF10B981)
val billing_expense = Color(0xFFEF4444)

val message_like_bg_dark = Color(0xFF064E3B)
val message_comment_bg_dark = Color(0xFF1E3A8A)
val message_default_bg_dark = Color(0xFF78350F)
val billing_income_dark = Color(0xFF34D399)
val billing_expense_dark = Color(0xFFF87171)