[package]
name = "mc2mt"           
version = "1.0.0"         
authors = ["Voltual", "CAN"]
edition = "2021"           

[lib]
name = "mc2mt"            
crate-type = ["cdylib", "rlib"] # 增加 rlib 使得 bin 能静态链接 lib 中导出的解析方法

[[bin]]
name = "mc2mt-cli"
path = "src/main.rs"

[dependencies]
jni = "0.21"               
log = "0.4"
android_logger = "0.13"
flate2 = "1.0"
byteorder = "1.4"
rusqlite = { version = "0.29", features = ["bundled"] }
rayon = "1.8"
once_cell = "1.18"