name: Rust-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 缓存工具链
      - name: Cache Rust & Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
            tools/.cargo/
            tools/.rustup/
          key: ${{ runner.os }}-rust-ndk-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-ndk-

      - name: Build Targets
        run: bash ./buildall.sh

      # 上传 Linux x86_64
      - name: Upload x86_64 Executable
        uses: actions/upload-artifact@v4
        with:
          name: mc2mt-cli-linux-x64
          path: rust/target/release/mc2mt-cli

      # 上传能在 Termux 原生直接免 root 运行的 Bionic 原生 Aarch64 独立程序
      - name: Upload Termux Aarch64 Executable
        uses: actions/upload-artifact@v4
        with:
          name: mc2mt-cli-termux-aarch64
          path: rust/target/aarch64-linux-android/release/mc2mt-cli